enableGlobalCache: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

npmRegistryServer: "http://npm.lstack-inner.cn/"

unsafeHttpWhitelist:
  - localhost
  - "*.lstack-inner.cn"
  - lstack-inner.cn

yarnPath: .yarn/releases/yarn-3.0.2.cjs
